# Generated by Django 4.2.8 on 2024-02-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainApp', '0002_remove_productcomments_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, verbose_name='isim')),
                ('surname', models.TextField(max_length=50, verbose_name='soy isim')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(max_length=50, verbose_name='telefon numarasi')),
                ('message', models.TextField(verbose_name='mesaj notu')),
            ],
        ),
    ]
