# Generated by Django 4.2.8 on 2024-02-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Sehir'),
        ),
        migrations.AlterField(
            model_name='productcomments',
            name='city',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Sehir'),
        ),
    ]
