# Generated by Django 4.2.8 on 2024-02-20 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0002_alter_customuser_city_alter_productcomments_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='p_special_status',
            field=models.ManyToManyField(blank=True, null=True, to='userApp.specialstatus'),
        ),
    ]
