# Generated by Django 4.2.8 on 2024-02-20 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0003_alter_products_p_special_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='p_special_status',
            field=models.ManyToManyField(blank=True, to='userApp.specialstatus'),
        ),
    ]
