# Generated by Django 4.2.8 on 2024-02-20 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0004_alter_products_p_special_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='p_img',
            field=models.ImageField(max_length=300, null=True, upload_to='', verbose_name='urun resmi'),
        ),
    ]
