# Generated by Django 4.2.8 on 2024-02-20 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0005_products_p_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcomments',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productcomments',
            name='user',
        ),
        migrations.RemoveField(
            model_name='products',
            name='p_category',
        ),
        migrations.RemoveField(
            model_name='products',
            name='p_special_status',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='ProductComments',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.DeleteModel(
            name='SpecialStatus',
        ),
    ]
