# Generated by Django 4.2.8 on 2024-03-02 20:53

from django.db import migrations, models
import userApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0009_alter_productcomments_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=userApp.models.profile_img_directory, verbose_name='profil_resmi'),
        ),
    ]
